name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t custom-java-chrome-ffmpeg .

    - name: Save Docker image to tar file
      run: |
            docker save -o custom-java-chrome-ffmpeg.tar custom-java-chrome-ffmpeg
            tar -czf custom-java-chrome-ffmpeg.tar.gz custom-java-chrome-ffmpeg.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: custom-java-chrome-ffmpeg
        path: custom-java-chrome-ffmpeg.tar.gz
