name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
          --platform ${{ matrix.platform }} \
          -t myapp:${{ github.sha }} .

      - name: Save image as .tar.gz
        run: |
          platform_suffix="${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}"
          docker save myapp:${{ github.sha }} | gzip > myapp-${platform_suffix}.tar.gz

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: myapp-*.tar.gz
