name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t custom-java-chrome-ffmpeg .

    # - name: Save Docker image to tar file
    #   run: |
    #         docker save -o custom-java-chrome-ffmpeg.tar custom-java-chrome-ffmpeg

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: custom-java-chrome-ffmpeg
    #     path: custom-java-chrome-ffmpeg.tar

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        registry: crpi-lltnojaasd01wldz.cn-guangzhou.personal.cr.aliyuncs.com
        # Username used to log against the Docker registry
        username: ${{ secrets.ALIYUN_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - run: |
          docker tag docker-java-chrome-ffmpeg:latest crpi-lltnojaasd01wldz.cn-guangzhou.personal.cr.aliyuncs.com/mrhadess/docker-java-chrome-ffmpeg:latest
          docker push crpi-lltnojaasd01wldz.cn-guangzhou.personal.cr.aliyuncs.com/mrhadess/docker-java-chrome-ffmpeg:latest
