name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t custom-java-chrome-ffmpeg .

    - name: Save Docker image to tar file
      run: |
            docker save -o custom-java-chrome-ffmpeg.tar custom-java-chrome-ffmpeg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: custom-java-chrome-ffmpeg
        path: custom-java-chrome-ffmpeg.tar

    - name: Push to Aliyun ACR
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
    - run: docker push crpi-lltnojaasd01wldz.cn-guangzhou.personal.cr.aliyuncs.com/test-space/custom-java-chrome-ffmpeg:latest
